# Generated by Django 4.1.1 on 2022-09-25 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("convertapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="file",
            field=models.FileField(blank=True, upload_to="uploads"),
        ),
    ]
