# Generated by Django 4.1.1 on 2022-09-25 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("convertapp", "0002_file_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="file",
            name="extension",
        ),
        migrations.RemoveField(
            model_name="file",
            name="name",
        ),
    ]
