# Generated by Django 4.1.1 on 2022-09-25 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("convertapp", "0003_remove_file_extension_remove_file_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="name",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
